### PR TITLE
Initial commit for graphical_group_01 (working name)

### PR DESCRIPTION
**Pull request by fcole90**
This creates our initial project directory with few initial files. Nothing relevant yet.

### CODE REVIEW

**Comment by assamite** [comment]
Great that you have forked the repository and initialised work on your fork. Unfortunately, I can not merge the pull request as it is now, as you have not done all the things required. See the section "The first pull request" (items 3-8) in [the repository's README](https://github.com/assamite/cc-course19#the-first-pull-request).

**Comment by fcole90** [comment]
Updated to follow guidelines. It adds a requirement for Pillow dependency.

**Comment by fcole90** [comment]
Can you clear a bit about the method required signatures? In the readme it says that the create method should return our artifact, but actually it seems that a list of tuples is required instead (according to examples). Can this be cleared out? Also, which parameters are the function expected to be taking?

**Comment by assamite** [comment]
Thanks for the input! Indeed, now I see that README and `create`-method's docstring might be seen conflicting. Method's docstring is the one that should be followed here. I'll clarify it in the README. Also `create`-method's input parameter specifications are mentioned in the method's docstring. However, we will come to them more closely in the following weeks. Right now it is sufficient that every group has output in the specified format.

**Pull request merged**
